# Generated by Django 4.2.5 on 2023-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DANI_NAIL_ART', '0002_agendar_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar_cita',
            name='tipoServicio',
            field=models.CharField(choices=[('manicure semipermanente', 'Manicure Semipermanente'), ('pedicure semipermanente', 'Pedicure Semipermanente'), ('uñas en polygel', 'Uñas en PolYgel')], max_length=50),
        ),
    ]
