# Generated by Django 4.2.4 on 2023-09-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DANI_NAIL_ART', '0003_alter_agendar_cita_tiposervicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrarse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=150)),
            ],
        ),
    ]
