# Generated by Django 4.2.5 on 2023-09-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DANI_NAIL_ART', '0004_registrarse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrar_Empleado',
        ),
        migrations.DeleteModel(
            name='registrarse',
        ),
    ]
