# Generated by Django 4.2.5 on 2023-09-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DANI_NAIL_ART', '0006_cita_registrar_empleado_registrarse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar_Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoServicio', models.CharField(choices=[('manicure semipermanente', 'Manicure Semipermanente'), ('pedicure semipermanente', 'Pedicure Semipermanente'), ('uñas en polygel', 'Uñas en PolYgel')], max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
